import {
    REACT_APP_BACKEND_HOST_DEV,
    REACT_APP_BACKEND_HOST_PROD,
    REACT_APP_REDIRECT_HOST
} from "react-native-dotenv";

const BACKEND_HOST = (__DEV__)
    ? REACT_APP_BACKEND_HOST_DEV
    : REACT_APP_BACKEND_HOST_PROD;

const REDIRECT_HOST = REACT_APP_REDIRECT_HOST;

const APP_OWNER = "tdp2-grupo4";

const APP_NAME = "TicketApp";

export {
    BACKEND_HOST, APP_OWNER, APP_NAME, REDIRECT_HOST
};
